# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  arcabeeapi:
    image: arcabeeapi
    build:
      context: .
      dockerfile: Arcabee.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5249:5249
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
